language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - sudo -H pip install awscli

install: true

script:
  - go test -v ./...

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - 'if [ "$BRANCH" == "master" ]; then
    ./scripts/build.sh;
    ./scripts/upload.sh;
    fi'
